# Generated by Django 5.2.7 on 2025-10-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_delete_otp"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatmessage",
            options={
                "ordering": ["created_at"],
                "permissions": [
                    ("chat_with_customer", "Can chat with customer"),
                    ("chat_with_delivery_partner", "Can chat with delivery partner"),
                ],
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(
                max_length=20, unique=True, verbose_name="Mobile Number"
            ),
        ),
    ]
